"use client";

import { useState } from "react";
import SearchIcon from "@mui/icons-material/Search";
import FilterListIcon from "@mui/icons-material/FilterList";
import { Dropdown } from "@/features/admin/components/dropdown";
import { Table } from "@/features/admin/components/table";

type GeneratedReport = {
  id: string;
  title: string;
  type: string;
  source: string;
  status: string;
  generated_by: string;
  generated_at: string;
};

function getStatusBadgeClass(status: string) {
  switch (status) {
    case "ready":
      return "bg-green-50 text-green-700";
    case "queued":
      return "bg-yellow-50 text-yellow-700";
    case "review_needed":
      return "bg-red-50 text-red-700";
    default:
      return "bg-[#EEF4FB] text-[#0985E7]";
  }
}

function formatStatus(status: string) {
  return status.replace("_", " ");
}

function formatDate(value: string) {
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? value : date.toLocaleDateString();
}

export function GeneratedReportsTable({ reports }: { reports: GeneratedReport[] }) {
  const [search, setSearch] = useState("");
  const [typeFilter, setTypeFilter] = useState("all");
  const [statusFilter, setStatusFilter] = useState("all");
  const [sortOrder, setSortOrder] = useState("latest");

  const types = [...new Set(reports.map((report) => report.type))];
  const statuses = [...new Set(reports.map((report) => report.status))];

  const filtered = reports
    .filter((report) => {
      const searchTerm = search.toLowerCase();
      const matchesSearch =
        report.title.toLowerCase().includes(searchTerm) ||
        report.source.toLowerCase().includes(searchTerm) ||
        report.generated_by.toLowerCase().includes(searchTerm);
      const matchesType = typeFilter === "all" || report.type === typeFilter;
      const matchesStatus = statusFilter === "all" || report.status === statusFilter;

      return matchesSearch && matchesType && matchesStatus;
    })
    .sort((a, b) => {
      const diff = new Date(b.generated_at).getTime() - new Date(a.generated_at).getTime();
      return sortOrder === "latest" ? diff : -diff;
    });

  return (
    <article className="flex flex-1 flex-col overflow-hidden rounded-2xl border border-[#E4EEF9] bg-white">
      <div className="flex flex-wrap items-center gap-3 border-b border-[#E4EEF9] px-6 py-4">
        <h2 className="text-lg font-black text-[#0C2B49]">All Generated Reports</h2>
        <div className="ml-auto flex flex-wrap items-center gap-3">
          <div className="flex items-center gap-2 rounded-xl border border-[#E4EEF9] bg-[#F8FBFF] px-3 py-2">
            <SearchIcon fontSize="small" className="text-[#64748b]" />
            <input
              type="text"
              placeholder="Search report, source, owner..."
              value={search}
              onChange={(event) => setSearch(event.target.value)}
              className="w-56 bg-transparent text-sm font-semibold text-[#0C2B49] outline-none placeholder:text-[#94a3b8]"
            />
          </div>
          <Dropdown
            icon={<FilterListIcon fontSize="small" className="text-[#64748b]" />}
            value={typeFilter}
            onChange={setTypeFilter}
            options={[{ label: "All Types", value: "all" }, ...types.map((type) => ({ label: type, value: type }))]}
          />
          <Dropdown
            value={statusFilter}
            onChange={setStatusFilter}
            options={[
              { label: "All Status", value: "all" },
              ...statuses.map((status) => ({
                label: formatStatus(status).replace(/\b\w/g, (char) => char.toUpperCase()),
                value: status,
              })),
            ]}
          />
          <Dropdown
            value={sortOrder}
            onChange={setSortOrder}
            options={[
              { label: "Latest", value: "latest" },
              { label: "Oldest", value: "oldest" },
            ]}
          />
        </div>
      </div>
      <Table
        columns={[
          { key: "title", label: "Report", render: (report) => <span className="font-semibold text-[#0C2B49]">{report.title}</span> },
          { key: "type", label: "Type", render: (report) => <span className="rounded-full bg-[#EEF4FB] px-2.5 py-1 text-xs font-black text-[#0985E7]">{report.type}</span> },
          { key: "source", label: "Source", render: (report) => <span className="text-[#64748b]">{report.source}</span> },
          { key: "status", label: "Status", render: (report) => <span className={`rounded-full px-2.5 py-1 text-xs font-bold capitalize ${getStatusBadgeClass(report.status)}`}>{formatStatus(report.status)}</span> },
          { key: "generatedBy", label: "Generated By", render: (report) => <span className="text-[#0C2B49]">{report.generated_by}</span> },
          { key: "date", label: "Generated", render: (report) => <span className="text-[#64748b] tabular-nums">{formatDate(report.generated_at)}</span> },
        ]}
        data={filtered}
        keyExtractor={(report) => report.id}
        emptyMessage="No generated reports found."
      />
    </article>
  );
}
